platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk'

inputs:
  - name: ExpenseTracker

outputs:
  - name: build-output

run:
  path: bash
  args:
  - -exc
  - |
    cd expenseTracker
    chmod +x gradlew
    ./gradlew build
    cp build/libs/expenseTracker.jar ../build-output