---
resources:
- name: expenseTracker
  type: git
  source:
    uri: {{github-repository}}
    branch: master
    private_key: {{github-private-key}}

- name: deployExpense
  type: cf
  source:
    api: {{cf-api-url}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: expenseReview

jobs:
- name: build
  plan:
  - get: expenseTracker
    trigger: true
  - task: build and test
    file: expenseTracker/ci/build.yml
    params:
      file: build-output/expenseTracker-*.jar

- name: deploy
  plan:
  - get: expenseTracker
    trigger: true
    passed: [build]
  - put: deployExpense
    params:
      path: expenseTracker-artifacts/expenseTracker-*.jar
      environment_variables:
        WELCOME_MESSAGE: "Expense Tracker in review environment"