resources:
- name: expense-tracker
  type: git
  source:
   uri: {{github-repository}}
   branch: master
   private_key: {{github-private-key}}

- name: expense-tracker-artifacts
  type: s3
  source:
    bucket: {{aws-bucket}}
    regexp: releases/expense-tracker.jar
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: deployment
  type: cf
  source:
   api: {{cf-api-url}}
   username: {{cf-username}}
   password: {{cf-password}}
   organization: {{cf-org}}
   space: review

jobs:
- name: build
  plan:
  - get: expense-tracker
    trigger: true
  - task: build and test
    file: expense-tracker/ci/build.yml
  - put: expense-tracker-artifacts
    params:
      file: build-output/expense-tracker.jar

- name: deploy
  plan:
  - get: expense-tracker
  - get: expense-tracker-artifacts
    trigger: true
    passed: [build]
  - put: deployment
    params:
     path: expense-tracker-artifacts/expense-tracker.jar
