  resources:
- name: ExpenseTracker
  type: git
  source:
   uri: {{github-repository}}
   branch: master
   private_key: {{github-private-key}}

- name: ExpenseTracker-artifacts
  type: s3
  source:
    bucket: {{aws-bucket}}
    regexp: releases/expenseTracker.jar
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: deployment
  type: cf
  source:
   api: {{cf-api-url}}
   username: {{cf-username}}
   password: {{cf-password}}
   organization: {{cf-org}}
   space: review

jobs:
- name: build
  plan:
  - get: ExpenseTracker
    trigger: true
  - task: build and test
    file: expenseTracker/ci/build.yml
  - put: ExpenseTracker-artifacts
    params:
      file: build-output/expenseTracker.jar

- name: deploy
  plan:
  - get: ExpenseTracker
  - get: ExpenseTracker-artifacts
    trigger: true
    passed: [build]
  - put: deployment
    params:
     path: ExpenseTracker-artifacts/expenseTracker.jar
